name: TheBlackLion
favicon: null
layout_spectrum: 0.47863
typography_spectrum: 0.50121
title: TheBlackLion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c81f18'
    - '#eea534'
    - '#e07025'
    - '#644225'
  brandStrength: 0.2534903532359749
  lightness: 0.28204879839904606
  saturation: 0.31327037839218974
  rhythmicContrast: 0.20839327829889953
purpose: []
