name: TheBlackLion
favicon: null
layout_spectrum: 0.24494611145928502
typography_spectrum: 0.20212304964661598
title: TheBlackLion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2534903532359749
  lightness: 0.28204879839904606
  saturation: 0.31327037839218974
  rhythmicContrast: 0.20839327829889953
purpose: []
